name: Name Greeter Action

description: 'An action that greets a user by name'

inputs:
  name:
    description: 'Name to greet'
    required: true

outputs:
  greeting:
    description: 'Greeting message'
    value: ${{ steps.greeting-step.outputs.greeting }}

runs:
  using: 'composite'
  steps:
    - id: greeting-step
      shell: bash
      run: ${{ github.action_path }}/greet.sh "${{ inputs.name }}"
