name: Reusable Greet Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name for the job'
        required: false
        default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # - run: echo "Hello from the reusable greet workflow!"

      # - run: |
      #     echo "Output from the reusable workflow: ${{ steps.step_with_output.outputs.greeting }}"
      #   name: Read Greeting Output

      - uses: ./new-greeter
        id: step_with_output
        with:
          name: ${{ inputs.name || 'World' }}

      - run: |
          echo "Output from the reusable action: ${{ steps.step_with_output.outputs.greeting }}
          echo "something again"
        name: Read Greeting Output
