name: Reusable Greet Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name for the job'
        required: false
        default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from the reusable greet workflow!"

      - run: echo "Hello, ${{ github.event.inputs.name }}! Welcome to the reusable greet workflow!"

